name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Prep
      run: |
          echo "NUGET_URL=https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        source-url: ${{ env.NUGET_URL }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build --no-restore --configuration Release
        dotnet pack --configuration Release
    - name: Test
      run: dotnet test --verbosity normal
    - name: Publish
      run: |
        dotnet nuget push **/*.nupkg \
          --source ${{ env.NUGET_URL }} \
          --skip-duplicate \
          --api-key ${{ secrets.API_TOKEN }}